fix: error handling

diff --git a/hooks/scripts/commitlint b/hooks/scripts/commitlint
--- a/hooks/scripts/commitlint
+++ b/hooks/scripts/commitlint
@@ -1,6 +1,11 @@
 #!/bin/bash
 set -euo pipefail
 
+fail() {
+    printf '%s\n' "$1" >&2
+    exit "${2-1}"
+}
+
 debug() {
     [ -z ${BUILDKITE_PLUGIN_COMMITLINT_DEBUG+x} ] || echo "[DEBUG] : $*" >&2
 }
@@ -21,6 +26,11 @@ commits=$(curl -Ls \
     -H "Authorization: Bearer $BUILDKITE_PLUGIN_COMMITLINT_GITHUB_TOKEN" \
     -H "X-GitHub-Api-Version: 2022-11-28" \
     "https://api.github.com/repos/$owner/$repo/pulls/$BUILDKITE_PULL_REQUEST/commits") || exit $?
+
+error=$(echo "$commits" | jq 'has("message")')
+if [ $error == "true" ]; then
+    fail "Unexpected payload: $error"
+fi
 
 debug "Commits: $commits"
 
